const hard = {
    en: {
        examiner:1,
        excitement:2,
        firefighter:3,
        flavour:4,
        guide:5,
        grateful:6,
        handkerchief:7,
        honest:8,
        independent:9,
        importance:10,
        judge:11,
        ladder:12,
        leisure:13,
        luggage:14,
        microwave:15,
        miserable:16,
        nearby:17,
        niece:18,
        occupation:19,
        outdoor:20,
        obviously:21,
        pattern:22,
        pence:23,
        professor:24,
        site:25,
        steak:26,
        terrific:27,
        unless:28,
        wardrobe:29,
    },
    uz: {
        imtihonchi: 1,
        hayajon: 2,
        "o't o'chiruvchi": 3,
        lazzat: 4,
        "qo'llanma": 5,
        minnatdor: 6,
        "ro'molcha": 7,
        halol: 8,
        mustaqil: 9,
        ahamiyati: 10,
        hakam: 11,
        narvon: 12,
        "dam olish": 13,
         bagaj: 14,
        "mikroto'lqinli pech": 15,
        baxtsiz: 16,
        yaqin:17,
        jiyan: 18,
        kasb: 19,
        tashqarida: 20,
        aniq: 21,
        naqsh: 22,
        pens: 23,
        professor: 24,
        sayt: 25,
        biftek: 26,
        ajoyib: 27,
        agar: 28,
        shkaf: 29,
    }
}