const medium = {
  en: {
    alive: 1,
    aloud: 2,
    already: 3,
    allow: 4,
    achieve: 5,
    amazing: 6,
    afford: 7,
    blame: 8,
    belong: 9,
    benefit: 10,
    blow: 11,
    brake: 12,
    brave: 13,
    bunch: 14,
    bored: 15,
    century: 16,
    careful: 17,
    celebrate: 18,
    cancel: 19,
    challenge: 20,
    chain: 21,
    chapter: 22,
    castle: 21,
    dangerous: 23,
    delivery: 24,
    direction: 25,
    disappear: 26,
    describe: 27,
    enemy: 28,
    entrance: 29,
    expedition: 30,
    effect: 31,
    excellent: 32,
    exchange: 33,
    follow: 34,
    fog: 35,
    further: 36,
    generation: 37,
    gentle: 38,
  },
  uz: {
    tirik: 1,
    "baland ovozda": 2,
    allaqachon: 3,
    "ruxsat berish": 4,
    erishish: 5,
    ajoyib: 6,
    imkon: 7,
    ayb: 8,
    tegishli: 9,
    foyda: 10,
    zarba: 11,
    tormoz: 12,
    jasur: 13,
    "to'plam": 14,
    zerikkan: 15,
    asr: 16,
    "ehtiyot bo'ling": 17,
    nishonlash: 18,
    "bekor qilish": 19,
    qiyinchilik: 20,
    zanjir: 21,
    bob: 22,
    "qal'a": 21,
    xavfli: 23,
    yetkazmoq: 24,
    "yo'nalish": 25,
    "g'oyib bo'lmoq": 26,
    tasvirlamoq: 27,
    dushman: 28,
    kirish: 29,
    ekspeditsiya: 30,
    tasir: 31,
    "a'lo": 32,
    almashmoq: 33,
    "kuzatib bormoq": 34,
    tuman: 35,
    yana: 36,
    avlod: 37,
    yumshoq: 38,
  },
};
